/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package tpzip;
import java.util.Arrays;
import java. util. Scanner;
import net.lingala.zip4j.ZipFile;
import net.lingala.zip4j.exception.ZipException;
import org.apache.commons.cli.*;

public class App {

    private static boolean eclair(String[] args) throws ZipException, ParseException {
        Options options = new Options();
        options.addOption("x", true, "extract");
        options.addOption("c", true, "zip");
        CommandLineParser parser = new DefaultParser();
        CommandLine cmd = parser.parse( options, args);
        if(cmd.hasOption("x")) {
            String zipFile = cmd.getOptionValue('x');
            String[] arguments= cmd.getArgs();
            for (String str:arguments){
                new ZipFile(zipFile).addFile(str);
            }
        }
        else if(cmd.hasOption("c")){
            String zipFile = cmd.getOptionValue('c');
            String[] arguments= cmd.getArgs();
            new ZipFile(zipFile).extractAll(arguments[0]);
        }
        else {
            return false;
        }
        return true;
    }
    public static void main(String[] args) {
        try{
         if(!eclair(args)){
             System.out.println("la commande que vous avez écrit est erronée");
         }
        }
        catch(Exception ex){
            System.out.println(ex.getMessage());
        }
    }
    }