/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package tpzip;
import java.util.Arrays;
import java. util. Scanner;
import net.lingala.zip4j.ZipFile;
import net.lingala.zip4j.exception.ZipException;

// eclair -c mon_archive.zip fichier1.txt fichier2.jpg fichier3.wav
// eclair -x mon_archive.zip $HOME/Documents
public class App {

    private static boolean eclair() throws ZipException {
        Scanner scanner = new Scanner( System. in);
        String inputString = scanner. nextLine();
        String[] arrOfStr = inputString.split(" ");
        if (!arrOfStr[0].equals("eclair")) return false;
        if(arrOfStr[1] .equals( "-x")){
            new ZipFile(arrOfStr[2]).extractAll(arrOfStr[3]);
        }
        else if(arrOfStr[1].equals("-c")){
            String[] tmpArr =Arrays.copyOfRange(arrOfStr,3,arrOfStr.length-1);
            for (String str:tmpArr){
                new ZipFile(arrOfStr[2]).addFile(str);
            }
        }
        else return false;
        return true;
    }
    public static void main(String[] args) {
        try{
         if(!eclair()){
             System.out.println("la commande que vous avez écrit est erronée");
         }
        }
        catch(Exception ex){
            System.out.println(ex.getMessage());
        }
    }
    }